import { db, productsTable } from "@workspace/db";

const img = {
  shoes: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
  apparel: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
  electronics: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
  home: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
  kitchen: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
  accessories: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80",
  beauty: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80",
  outdoor: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80",
  books: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80",
  toys: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&q=80",
  sports: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
  furniture: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
  gaming: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80",
  pets: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&q=80",
  health: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80",
  stationery: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80",
  baby: "https://images.unsplash.com/photo-1567716661677-3ac9f45b8dd8?w=800&q=80",
  watches: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80",
  bags: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
  food: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
};

type Cat = keyof typeof img;
type P = { name: string; desc: string; cat: Cat; price: number; stock: number; colors?: string[]; type: string; tags: string[] };

const products: P[] = [
  // ── SHOES (20) ──
  { name:"Air Force Classic Low", desc:"Iconic white leather low-top sneaker with cushioned sole.", cat:"shoes", price:45, stock:50, colors:["White","Black"], type:"Sneaker", tags:["casual","trending"] },
  { name:"Canvas High-Top Sneaker", desc:"Vulcanised canvas high-top in bold colours. Street style staple.", cat:"shoes", price:22, stock:60, colors:["Black","Red","White"], type:"Sneaker", tags:["casual","classic"] },
  { name:"Chelsea Suede Boot", desc:"Slip-on suede Chelsea boots with elastic panels and chunky sole.", cat:"shoes", price:67, stock:25, colors:["Tan","Black","Navy"], type:"Boots", tags:["winter","premium"] },
  { name:"Oxford Brogue Leather", desc:"Full-grain leather brogues with cap-toe detailing.", cat:"shoes", price:58, stock:30, colors:["Brown","Black"], type:"Formal", tags:["formal","office"] },
  { name:"Runner Pro Lightweight", desc:"Breathable mesh running shoe with responsive foam midsole.", cat:"shoes", price:38, stock:55, colors:["Black/Red","Grey/Blue"], type:"Running", tags:["sport","gym"] },
  { name:"Raffia Woven Sandals", desc:"Handcrafted raffia sandals with leather straps. Eco-friendly.", cat:"shoes", price:9, stock:45, colors:["Natural","Black"], type:"Sandals", tags:["casual","eco"] },
  { name:"Platform Chunky Loafer", desc:"Faux leather chunky platform loafer with gold hardware.", cat:"shoes", price:31, stock:35, colors:["Beige","Black"], type:"Loafers", tags:["fashion","statement"] },
  { name:"Satin Kitten Heel", desc:"Elegant pointed-toe satin kitten heel for evening wear.", cat:"shoes", price:27, stock:30, colors:["Nude","Black","Wine"], type:"Heels", tags:["elegant","evening"] },
  { name:"Trail Hiking Boot", desc:"Waterproof lace-up hiking boot with Vibram outsole.", cat:"shoes", price:75, stock:20, colors:["Brown","Olive"], type:"Boots", tags:["outdoor","adventure"] },
  { name:"Canvas Print Slides", desc:"Bold patterned EVA slides, lightweight for everyday wear.", cat:"shoes", price:12, stock:65, colors:["Multi"], type:"Slides", tags:["summer","casual"] },
  { name:"Mesh Speed Trainer", desc:"Ultra-lightweight cross-trainer with knit upper.", cat:"shoes", price:49, stock:40, colors:["White","Black","Teal"], type:"Trainer", tags:["gym","sport"] },
  { name:"Derby Formal Shoe", desc:"Classic cap-toe derby in polished calfskin.", cat:"shoes", price:62, stock:20, colors:["Black","Dark Brown"], type:"Formal", tags:["office","formal"] },
  { name:"Espadrille Slip-On", desc:"Jute-sole canvas espadrille in summer-ready pastels.", cat:"shoes", price:18, stock:50, colors:["Navy","White","Sage"], type:"Casual", tags:["summer","casual"] },
  { name:"Ankle Strap Block Heel", desc:"Block-heel sandal with buckle ankle strap and cushioned footbed.", cat:"shoes", price:34, stock:28, colors:["Camel","Black","White"], type:"Heels", tags:["evening","fashion"] },
  { name:"Slip-On Mule", desc:"Backless leather mule with padded insole. Office to evening.", cat:"shoes", price:41, stock:32, colors:["Nude","Black"], type:"Mule", tags:["casual","office"] },
  { name:"Waterproof Rain Boot", desc:"Pull-on rubber rain boot with fleece lining and non-slip sole.", cat:"shoes", price:29, stock:35, colors:["Black","Navy","Red"], type:"Boots", tags:["rain","winter"] },
  { name:"Retro Basketball Shoe", desc:"High-top leather basketball sneaker with padded collar.", cat:"shoes", price:55, stock:30, colors:["White/Red","Black/Gold"], type:"Sneaker", tags:["retro","sport"] },
  { name:"Gladiator Flat Sandal", desc:"Multi-strap gladiator sandal with adjustable buckles.", cat:"shoes", price:16, stock:45, colors:["Tan","Black","Gold"], type:"Sandals", tags:["summer","fashion"] },
  { name:"Knit Slip-On Trainer", desc:"Sock-style knit upper trainer with memory foam insole.", cat:"shoes", price:33, stock:55, colors:["Grey","Black","Navy"], type:"Trainer", tags:["casual","comfort"] },
  { name:"Cowboy Ankle Boot", desc:"Western-inspired ankle boot with stacked heel and pointed toe.", cat:"shoes", price:72, stock:18, colors:["Tan","Black"], type:"Boots", tags:["western","fashion"] },
  // ── APPAREL (20) ──
  { name:"Oversized Graphic Tee", desc:"100% cotton oversized tee with street-inspired graphic print.", cat:"apparel", price:8, stock:80, colors:["Black","White","Grey"], type:"T-Shirt", tags:["streetwear","casual"] },
  { name:"Slim-Fit Chinos", desc:"Stretch cotton slim-fit chinos with flat front.", cat:"apparel", price:19, stock:55, colors:["Khaki","Navy","Olive","Black"], type:"Pants", tags:["smart-casual","office"] },
  { name:"Silk Wrap Blouse", desc:"Flowy silk-effect wrap blouse with V-neckline and tie waist.", cat:"apparel", price:16, stock:45, colors:["Ivory","Blush","Emerald"], type:"Top", tags:["office","elegant"] },
  { name:"Denim Jacket Vintage", desc:"Distressed vintage-wash denim jacket with raw hem.", cat:"apparel", price:29, stock:30, colors:["Light Blue","Dark Blue"], type:"Jacket", tags:["vintage","denim"] },
  { name:"Floral Midi Dress", desc:"Vibrant floral midi dress with puff sleeves and side pockets.", cat:"apparel", price:18, stock:40, colors:["Multi"], type:"Dress", tags:["summer","casual"] },
  { name:"Cotton Fleece Hoodie", desc:"Heavyweight cotton fleece hoodie with kangaroo pocket.", cat:"apparel", price:35, stock:55, colors:["Grey","Black","Navy"], type:"Hoodie", tags:["casual","cozy"] },
  { name:"Tailored 3-Piece Suit", desc:"Slim-fit Italian-cut wool-blend suit — jacket, trousers and waistcoat.", cat:"apparel", price:120, stock:10, colors:["Charcoal","Navy","Black"], type:"Suit", tags:["formal","premium"] },
  { name:"Hooded Trench Coat", desc:"Double-breasted trench coat with detachable hood.", cat:"apparel", price:95, stock:12, colors:["Camel","Black","Olive"], type:"Coat", tags:["winter","premium"] },
  { name:"Bomber Jacket", desc:"Classic nylon bomber jacket with ribbed cuffs and hem.", cat:"apparel", price:45, stock:25, colors:["Black","Olive","Navy"], type:"Jacket", tags:["casual","streetwear"] },
  { name:"Linen Relaxed Set", desc:"Relaxed linen top and pants in natural earth tones.", cat:"apparel", price:22, stock:35, colors:["Cream","Sky Blue","Olive"], type:"Set", tags:["casual","linen"] },
  { name:"Pleated Midi Skirt", desc:"Satin pleated midi skirt with elasticated waistband.", cat:"apparel", price:24, stock:38, colors:["Black","Dusty Rose","Forest Green"], type:"Skirt", tags:["elegant","versatile"] },
  { name:"Fitted Turtleneck", desc:"Ribbed cotton-modal turtleneck — a minimalist essential.", cat:"apparel", price:14, stock:60, colors:["Black","White","Cream","Red"], type:"Top", tags:["minimalist","basics"] },
  { name:"Wide-Leg Palazzo Pants", desc:"High-waist wide-leg palazzo pants in flowing chiffon.", cat:"apparel", price:21, stock:32, colors:["Black","White","Cobalt"], type:"Pants", tags:["fashion","statement"] },
  { name:"Puffer Gilet", desc:"Lightweight quilted puffer gilet with high collar.", cat:"apparel", price:38, stock:28, colors:["Black","Navy","Olive"], type:"Gilet", tags:["winter","layering"] },
  { name:"Cargo Jogger Pants", desc:"Multi-pocket cargo joggers in stretch cotton.", cat:"apparel", price:14, stock:65, colors:["Olive","Black","Khaki"], type:"Pants", tags:["casual","streetwear"] },
  { name:"Wrap Maxi Dress", desc:"Bohemian wrap maxi dress with floral print and flutter sleeves.", cat:"apparel", price:26, stock:35, colors:["Floral Multi"], type:"Dress", tags:["boho","summer"] },
  { name:"Oxford Button-Down Shirt", desc:"Classic Oxford cotton button-down. Business casual staple.", cat:"apparel", price:17, stock:55, colors:["White","Light Blue","Pink"], type:"Shirt", tags:["office","classic"] },
  { name:"Varsity Jacket", desc:"Wool-blend varsity jacket with leather sleeves.", cat:"apparel", price:65, stock:20, colors:["Black/White","Navy/Red"], type:"Jacket", tags:["retro","streetwear"] },
  { name:"Ribbed Knit Co-Ord Set", desc:"Matching ribbed knit crop top and high-waist skirt set.", cat:"apparel", price:28, stock:30, colors:["Beige","Brown","Black"], type:"Set", tags:["fashion","co-ord"] },
  { name:"Longline Cardigan", desc:"Oversized longline merino-blend cardigan with deep pockets.", cat:"apparel", price:42, stock:25, colors:["Oat","Charcoal","Sage"], type:"Knitwear", tags:["cozy","layering"] },
  // ── ELECTRONICS (20) ──
  { name:"ANC Wireless Headphones", desc:"40-hour active noise-cancelling headphones with premium drivers.", cat:"electronics", price:89, stock:20, colors:["Black","Silver"], type:"Headphones", tags:["audio","wireless"] },
  { name:"Smart Watch Pro", desc:"AMOLED health smartwatch with GPS and SpO2 sensor.", cat:"electronics", price:75, stock:25, colors:["Black","Rose Gold","Silver"], type:"Wearable", tags:["health","fitness"] },
  { name:"TWS Earbuds X7", desc:"True wireless earbuds, 6-hour playtime, IPX5 water resistant.", cat:"electronics", price:32, stock:50, colors:["White","Black"], type:"Earbuds", tags:["audio","sport"] },
  { name:"65W Fast Charger Hub", desc:"6-port USB-C hub with 65W PD fast charging.", cat:"electronics", price:18, stock:60, colors:["Black","White"], type:"Charger", tags:["accessories","charging"] },
  { name:"Bluetooth Speaker 360", desc:"IPX7 waterproof portable speaker, 24hr battery, 360 sound.", cat:"electronics", price:41, stock:35, colors:["Black","Navy","Red"], type:"Speaker", tags:["audio","outdoor"] },
  { name:"Mechanical Keyboard TKL", desc:"Tenkeyless RGB mechanical keyboard with tactile brown switches.", cat:"electronics", price:55, stock:20, colors:["Black","White"], type:"Keyboard", tags:["gaming","productivity"] },
  { name:"4K Webcam Ultra", desc:"4K autofocus webcam with built-in noise-cancelling mic.", cat:"electronics", price:47, stock:25, colors:["Black"], type:"Webcam", tags:["work","streaming"] },
  { name:"Wireless Charging Pad", desc:"15W Qi-certified wireless charging pad for all phones.", cat:"electronics", price:12, stock:80, colors:["Black","White"], type:"Charger", tags:["charging","wireless"] },
  { name:"Ring Light 18-inch", desc:"Professional 18-inch LED ring light with tripod and phone mount.", cat:"electronics", price:28, stock:30, colors:["White"], type:"Lighting", tags:["creator","studio"] },
  { name:"Power Bank 20000mAh", desc:"Slim 20,000mAh power bank with USB-A and USB-C output.", cat:"electronics", price:22, stock:70, colors:["Black","White"], type:"Power Bank", tags:["essential","travel"] },
  { name:"Mini Projector HD", desc:"1080p portable mini projector with built-in speaker, 200-inch display.", cat:"electronics", price:95, stock:12, colors:["White","Black"], type:"Projector", tags:["home cinema","portable"] },
  { name:"Laptop Stand Aluminium", desc:"Adjustable aluminium laptop stand with heat dissipation.", cat:"electronics", price:24, stock:45, colors:["Silver","Space Grey"], type:"Accessories", tags:["work","ergonomic"] },
  { name:"USB-C Multiport Hub 7-in-1", desc:"7-in-1 hub with 4K HDMI, SD card and 3x USB-A.", cat:"electronics", price:35, stock:40, colors:["Silver","Space Grey"], type:"Accessories", tags:["work","mac"] },
  { name:"Wireless Gaming Mouse", desc:"Ultralight wireless gaming mouse, 25K DPI, 70hr battery.", cat:"electronics", price:49, stock:28, colors:["Black","White"], type:"Mouse", tags:["gaming","wireless"] },
  { name:"Smart Plug 4-Pack", desc:"Wi-Fi smart plugs with energy monitoring and voice control.", cat:"electronics", price:19, stock:55, colors:["White"], type:"Smart Home", tags:["smart home","energy"] },
  { name:"E-Ink Reading Tablet", desc:"6-inch e-ink tablet with warm light and 6-week battery.", cat:"electronics", price:119, stock:15, colors:["Black","White"], type:"Tablet", tags:["reading","books"] },
  { name:"White Noise Sleep Machine", desc:"30 soothing sounds with timer for deep sleep.", cat:"electronics", price:27, stock:35, colors:["White","Grey"], type:"Wellness", tags:["sleep","wellness"] },
  { name:"Outdoor Security Camera HD", desc:"1080p Wi-Fi security camera with night vision.", cat:"electronics", price:38, stock:25, colors:["White","Black"], type:"Security", tags:["home security","smart home"] },
  { name:"USB Rechargeable Desk Fan", desc:"360 oscillating desk fan, 3 speeds, 12hr battery.", cat:"electronics", price:16, stock:60, colors:["White","Black"], type:"Appliance", tags:["summer","desk"] },
  { name:"LED Desk Lamp with Wireless Charge", desc:"Touch-dimmable LED lamp with 15W wireless charging base.", cat:"electronics", price:33, stock:30, colors:["White","Black"], type:"Lighting", tags:["desk","work"] },
  // ── HOME (20) ──
  { name:"Linen Throw Pillow Set", desc:"4 European linen throw pillows with removable covers.", cat:"home", price:16, stock:40, colors:["Beige","Grey","Terracotta"], type:"Bedding", tags:["decor","bedroom"] },
  { name:"Cotton Waffle Blanket", desc:"Lightweight 100% cotton waffle-knit throw blanket.", cat:"home", price:21, stock:30, colors:["White","Stone","Sage"], type:"Bedding", tags:["bedroom","cosy"] },
  { name:"Floating Wall Shelves 3-Pack", desc:"3 solid pine floating shelves with invisible brackets.", cat:"home", price:17, stock:25, colors:["Natural","White","Walnut"], type:"Furniture", tags:["storage","decor"] },
  { name:"Jute Area Rug 5x7", desc:"Hand-woven natural jute rug. Durable and eco-friendly.", cat:"home", price:38, stock:15, colors:["Natural","Grey"], type:"Rug", tags:["living room","eco"] },
  { name:"Macrame Wall Hanging", desc:"Hand-knotted bohemian macrame wall art in natural cotton.", cat:"home", price:13, stock:20, colors:["Natural"], type:"Decor", tags:["boho","art"] },
  { name:"Smart LED Bulbs 4-Pack", desc:"4x 9W WiFi smart bulbs with 16M colours and voice control.", cat:"home", price:19, stock:35, colors:["Multi"], type:"Lighting", tags:["smart home","lighting"] },
  { name:"Scented Soy Candle Set", desc:"Hand-poured soy candles: Amber, Sandalwood and Vanilla.", cat:"home", price:14, stock:60, colors:["Cream"], type:"Candles", tags:["aromatherapy","gift"] },
  { name:"Terracotta Pot Set", desc:"Handmade terracotta pots with saucers for succulents.", cat:"home", price:11, stock:45, colors:["Terracotta"], type:"Garden", tags:["plants","decor"] },
  { name:"Blackout Curtain Pair", desc:"100% blackout thermal eyelet curtains. Reduces heat and noise.", cat:"home", price:32, stock:30, colors:["Charcoal","Beige","Navy"], type:"Curtains", tags:["bedroom","living room"] },
  { name:"Bamboo Desk Organiser", desc:"6-slot bamboo desktop organiser for a tidy workspace.", cat:"home", price:9, stock:55, colors:["Natural"], type:"Storage", tags:["office","organisation"] },
  { name:"Reed Diffuser Set", desc:"100ml luxury reed diffuser, 8 reeds, 60-day fragrance.", cat:"home", price:18, stock:40, colors:["Clear"], type:"Fragrance", tags:["aromatherapy","gift"] },
  { name:"Abstract Canvas Print", desc:"Framed abstract canvas in earth tones. 60x80cm.", cat:"home", price:29, stock:20, colors:["Earth Tones"], type:"Art", tags:["wall art","modern"] },
  { name:"Wicker Storage Basket Set", desc:"3 seagrass wicker baskets with handles.", cat:"home", price:22, stock:25, colors:["Natural"], type:"Storage", tags:["storage","boho"] },
  { name:"Linen Duvet Cover Set", desc:"Stonewashed linen duvet cover with 2 pillowcases. King.", cat:"home", price:55, stock:18, colors:["White","Sage","Terracotta"], type:"Bedding", tags:["premium","bedroom"] },
  { name:"Velvet Cushion Cover Pair", desc:"Soft velvet cushion covers with hidden zip. 45x45cm.", cat:"home", price:12, stock:50, colors:["Emerald","Mustard","Navy"], type:"Bedding", tags:["decor","living room"] },
  { name:"Geometric Metal Wall Clock", desc:"Modern geometric clock in powder-coated metal. 40cm.", cat:"home", price:26, stock:22, colors:["Black","Gold","Rose Gold"], type:"Decor", tags:["modern","wall decor"] },
  { name:"Solar Garden Lights 8-Pack", desc:"8 solar-powered stake lights for pathways and gardens.", cat:"home", price:17, stock:40, colors:["Warm White"], type:"Lighting", tags:["garden","solar"] },
  { name:"Faux Sheepskin Rug", desc:"Fluffy faux sheepskin rug, machine washable, ultra-soft.", cat:"home", price:24, stock:30, colors:["Ivory","Charcoal"], type:"Rug", tags:["bedroom","cosy"] },
  { name:"Rattan Pendant Lamp", desc:"Natural rattan pendant lampshade with E27 fitting. Boho.", cat:"home", price:31, stock:20, colors:["Natural"], type:"Lighting", tags:["boho","pendant"] },
  { name:"Aromatherapy Diffuser 300ml", desc:"Ultrasonic oil diffuser with 7 LED colours and auto shut-off.", cat:"home", price:23, stock:35, colors:["White"], type:"Wellness", tags:["wellness","aromatherapy"] },
  // ── KITCHEN (20) ──
  { name:"Cast Iron Skillet 12 inch", desc:"Pre-seasoned 12-inch cast iron skillet, even heat distribution.", cat:"kitchen", price:28, stock:25, colors:["Black"], type:"Cookware", tags:["cooking","durable"] },
  { name:"Ceramic Non-Stick Pan Set", desc:"PFOA-free ceramic non-stick 3-piece set (20/24/28cm).", cat:"kitchen", price:45, stock:20, colors:["Stone","Sage","Rust"], type:"Cookware", tags:["healthy","cooking"] },
  { name:"Electric Blender 1500W", desc:"High-power blender with 1500W motor and 6 steel blades.", cat:"kitchen", price:35, stock:40, colors:["Silver/Black","White"], type:"Appliance", tags:["blending","smoothie"] },
  { name:"French Press Coffee Maker", desc:"Borosilicate glass French press with double-wall filter.", cat:"kitchen", price:24, stock:35, colors:["Black","Chrome"], type:"Coffee", tags:["coffee","morning"] },
  { name:"6-Piece Knife Block Set", desc:"German steel knife block set — ultra-sharp ergonomic blades.", cat:"kitchen", price:45, stock:20, colors:["Silver/Black"], type:"Cutlery", tags:["cooking","professional"] },
  { name:"Bamboo Cutting Board Set", desc:"S/M/L bamboo boards with juice grooves.", cat:"kitchen", price:12, stock:55, colors:["Natural"], type:"Prep", tags:["eco","prep"] },
  { name:"Stainless Pressure Pot 5L", desc:"Heavy-duty pressure pot — cook meals in half the time.", cat:"kitchen", price:22, stock:35, colors:["Silver"], type:"Cookware", tags:["cooking","essential"] },
  { name:"Digital Kitchen Scale", desc:"Precision digital scale, 0.1g accuracy, 5kg capacity.", cat:"kitchen", price:15, stock:50, colors:["Black","White"], type:"Tools", tags:["baking","precision"] },
  { name:"Glass Meal Prep Containers", desc:"Borosilicate glass containers with airtight lids. Set of 5.", cat:"kitchen", price:29, stock:40, colors:["Clear"], type:"Storage", tags:["meal prep","healthy"] },
  { name:"Rotating Spice Rack 24-Jar", desc:"Rotating spice rack with glass jars and chalkboard labels.", cat:"kitchen", price:19, stock:30, colors:["Chrome","Black"], type:"Storage", tags:["organisation","cooking"] },
  { name:"Air Fryer 4L Digital", desc:"4-litre digital air fryer with 8 presets and non-stick basket.", cat:"kitchen", price:49, stock:22, colors:["Black","White"], type:"Appliance", tags:["healthy","cooking"] },
  { name:"Stand Mixer 5-Speed", desc:"Tilt-head 4.5L stand mixer with dough hook and balloon whisk.", cat:"kitchen", price:79, stock:15, colors:["Red","Silver","Black"], type:"Appliance", tags:["baking","professional"] },
  { name:"Granite Mortar and Pestle", desc:"Unpolished granite mortar and pestle, 17cm diameter.", cat:"kitchen", price:16, stock:30, colors:["Grey"], type:"Tools", tags:["cooking","traditional"] },
  { name:"Pour-Over Coffee Set", desc:"Pour-over dripper, gooseneck kettle and glass server.", cat:"kitchen", price:38, stock:18, colors:["Black","White"], type:"Coffee", tags:["coffee","pour-over"] },
  { name:"Silicone Baking Mat 2-Pack", desc:"Non-stick silicone mat. Reusable, oven-safe to 230 C.", cat:"kitchen", price:11, stock:55, colors:["Red","Blue"], type:"Baking", tags:["baking","eco"] },
  { name:"Temperature Control Kettle 1.7L", desc:"6-preset electric kettle with keep-warm function.", cat:"kitchen", price:32, stock:25, colors:["Glass/Black"], type:"Appliance", tags:["tea","coffee"] },
  { name:"Microplane Grater Set", desc:"4 stainless microplanes for zesting, grating and slicing.", cat:"kitchen", price:14, stock:40, colors:["Silver/Black"], type:"Tools", tags:["cooking","prep"] },
  { name:"Ceramic Mixing Bowl Set", desc:"4 nesting ceramic mixing bowls with non-slip base.", cat:"kitchen", price:26, stock:28, colors:["Cream","Sage","Terracotta"], type:"Prep", tags:["baking","prep"] },
  { name:"Indoor Herb Garden Kit", desc:"Self-watering indoor herb garden — basil, mint and parsley.", cat:"kitchen", price:21, stock:30, colors:["White"], type:"Garden", tags:["herbs","healthy"] },
  { name:"Food Vacuum Sealer", desc:"Compact vacuum sealer with 10 bags. Extends freshness 5x.", cat:"kitchen", price:34, stock:22, colors:["Black","White"], type:"Storage", tags:["meal prep","food storage"] },
  // ── ACCESSORIES (20) ──
  { name:"RFID Slim Leather Wallet", desc:"RFID-blocking slim leather wallet with 6 card slots.", cat:"accessories", price:29, stock:50, colors:["Black","Brown","Tan"], type:"Wallet", tags:["gift","essentials"] },
  { name:"Polarised Sunglasses", desc:"UV400 polarised sunglasses with metal frame. Anti-glare.", cat:"accessories", price:24, stock:45, colors:["Black","Gold","Silver"], type:"Sunglasses", tags:["summer","driving"] },
  { name:"Canvas Tote Bag Large", desc:"Heavy-duty canvas tote with inner pocket and reinforced handles.", cat:"accessories", price:15, stock:65, colors:["Natural","Black","Navy"], type:"Bag", tags:["eco","everyday"] },
  { name:"Full-Grain Leather Belt", desc:"Full-grain leather belt with polished buckle.", cat:"accessories", price:22, stock:40, colors:["Black","Brown"], type:"Belt", tags:["formal","casual"] },
  { name:"Silk Scarf", desc:"Pure silk scarf with abstract print. Head, belt or bag accessory.", cat:"accessories", price:28, stock:35, colors:["Multi","Navy","Red"], type:"Scarf", tags:["gift","elegant"] },
  { name:"Natural Stone Bracelet Set", desc:"5 bracelets: Amazonite, Tiger Eye, Onyx, Lapis, Rose Quartz.", cat:"accessories", price:18, stock:55, colors:["Multi"], type:"Jewellery", tags:["boho","gift"] },
  { name:"Structured Baseball Cap", desc:"6-panel cotton cap with embroidered logo and curved brim.", cat:"accessories", price:9, stock:55, colors:["Black","White","Navy"], type:"Hat", tags:["casual","streetwear"] },
  { name:"Compact Windproof Umbrella", desc:"Auto open/close umbrella with UV coating and wind-resistant ribs.", cat:"accessories", price:19, stock:40, colors:["Black","Navy","Red"], type:"Umbrella", tags:["travel","essential"] },
  { name:"Chunky Knit Bobble Hat", desc:"Chunky knit beanie with pom-pom. One size.", cat:"accessories", price:7, stock:70, colors:["Grey","Cream","Camel","Black"], type:"Hat", tags:["winter","cozy"] },
  { name:"Cashmere Blend Gloves", desc:"Touchscreen-compatible cashmere gloves with ribbed cuffs.", cat:"accessories", price:16, stock:45, colors:["Black","Grey","Camel"], type:"Gloves", tags:["winter","soft"] },
  { name:"Pearl Drop Earrings", desc:"Freshwater pearl drops with gold-plated sterling silver posts.", cat:"accessories", price:24, stock:35, colors:["White","Pink"], type:"Jewellery", tags:["elegant","gift"] },
  { name:"Layered Necklace Set", desc:"3 gold-plated layered necklaces in varying lengths.", cat:"accessories", price:21, stock:40, colors:["Gold","Silver"], type:"Jewellery", tags:["trendy","gift"] },
  { name:"Tortoiseshell Hair Clip Set", desc:"6 resin tortoiseshell hair clips in various sizes.", cat:"accessories", price:8, stock:65, colors:["Tortoiseshell","Black","Clear"], type:"Hair", tags:["casual","hair"] },
  { name:"Wool Tartan Blanket Scarf", desc:"Oversized wool-blend tartan blanket scarf. 180x70cm.", cat:"accessories", price:25, stock:30, colors:["Tartan Red","Navy Tartan"], type:"Scarf", tags:["winter","cozy"] },
  { name:"Gold Chunky Ring Set", desc:"5 gold-plated statement rings in varying widths.", cat:"accessories", price:14, stock:50, colors:["Gold","Silver"], type:"Jewellery", tags:["trendy","stacking"] },
  { name:"Wide Brim Straw Hat", desc:"Natural straw wide-brim hat with ribbon band. UV protection.", cat:"accessories", price:19, stock:30, colors:["Natural","Black"], type:"Hat", tags:["summer","beach"] },
  { name:"Leather-End Suspenders", desc:"Y-back braces with genuine leather ends and metal clips.", cat:"accessories", price:18, stock:25, colors:["Black","Brown","Navy"], type:"Belt", tags:["formal","vintage"] },
  { name:"Pashmina Wrap", desc:"Lightweight 70% pashmina 30% silk wrap. 200x70cm.", cat:"accessories", price:22, stock:35, colors:["Camel","Blush","Ivory","Navy"], type:"Scarf", tags:["elegant","versatile"] },
  { name:"Art Deco Enamel Brooch", desc:"Art Deco enamel and crystal brooch on gold-tone base.", cat:"accessories", price:12, stock:40, colors:["Gold/Blue","Gold/Red"], type:"Jewellery", tags:["vintage","gift"] },
  { name:"Leather Luggage Tag Set", desc:"Genuine leather luggage tags with buckle strap. Set of 2.", cat:"accessories", price:13, stock:45, colors:["Tan","Black"], type:"Travel", tags:["travel","gift"] },
  // ── BEAUTY (20) ──
  { name:"Vitamin C Glow Serum", desc:"20% Vitamin C brightening serum for radiant even-toned skin.", cat:"beauty", price:19, stock:40, colors:[], type:"Skincare", tags:["brightening","serum"] },
  { name:"SPF 50 Tinted Sunscreen", desc:"Lightweight SPF 50+ tinted sunscreen for all skin tones.", cat:"beauty", price:14, stock:50, colors:["Light","Medium","Dark"], type:"Suncare", tags:["SPF","protection"] },
  { name:"Shea Butter Moisturiser 500ml", desc:"Raw unrefined shea butter with vitamin E.", cat:"beauty", price:7, stock:80, colors:[], type:"Skincare", tags:["natural","moisturiser"] },
  { name:"Perfume Oil Collection", desc:"5 long-lasting perfume oils: Oud, Amber, Musk, Floral, Citrus.", cat:"beauty", price:22, stock:30, colors:[], type:"Fragrance", tags:["oud","gift"] },
  { name:"Castor Oil Hair Growth Kit", desc:"Black castor oil with scalp massager and hot oil cap.", cat:"beauty", price:11, stock:55, colors:[], type:"Haircare", tags:["hair growth","natural"] },
  { name:"Long-Stay Matte Lipstick Set", desc:"6 long-wear matte lipsticks in diverse shades.", cat:"beauty", price:17, stock:45, colors:["Nude","Berry","Wine","Red"], type:"Makeup", tags:["lips","makeup"] },
  { name:"Jade Roller and Gua Sha Set", desc:"Genuine jade facial roller and gua sha. Boosts circulation.", cat:"beauty", price:8, stock:35, colors:["Green"], type:"Tools", tags:["facial","wellness"] },
  { name:"Aloe Vera Gel 300ml", desc:"100% pure aloe vera gel. Soothes, hydrates and styles.", cat:"beauty", price:6, stock:75, colors:[], type:"Skincare", tags:["soothing","natural"] },
  { name:"Rose Water Toner Mist", desc:"Pure rose water facial toner — hydrates and preps skin.", cat:"beauty", price:9, stock:60, colors:[], type:"Skincare", tags:["toning","hydration"] },
  { name:"Hyaluronic Acid Serum", desc:"3-weight hyaluronic acid for deep and surface hydration.", cat:"beauty", price:21, stock:40, colors:[], type:"Skincare", tags:["hydration","anti-aging"] },
  { name:"Retinol Night Cream", desc:"0.3% retinol and peptide night cream for cell renewal.", cat:"beauty", price:26, stock:30, colors:[], type:"Skincare", tags:["anti-aging","night"] },
  { name:"Derma Roller 0.5mm Titanium", desc:"540-needle titanium roller for collagen induction therapy.", cat:"beauty", price:12, stock:45, colors:[], type:"Tools", tags:["collagen","anti-aging"] },
  { name:"Foundation Brush Set 5pc", desc:"Professional 5-piece synthetic bristle brush set.", cat:"beauty", price:15, stock:45, colors:["Rose Gold"], type:"Makeup Tools", tags:["makeup","professional"] },
  { name:"Micellar Cleansing Water 400ml", desc:"Gentle micellar water — removes makeup without rinsing.", cat:"beauty", price:8, stock:65, colors:[], type:"Skincare", tags:["cleansing","sensitive"] },
  { name:"Korean Sheet Mask Bundle", desc:"10 hydrating sheet masks: Collagen, Niacinamide and Gold.", cat:"beauty", price:13, stock:60, colors:[], type:"Skincare", tags:["korean beauty","hydration"] },
  { name:"Argan Oil Deep Hair Mask", desc:"Argan oil deep conditioning mask. Repairs damage in 10 min.", cat:"beauty", price:10, stock:55, colors:[], type:"Haircare", tags:["hair repair","moisturising"] },
  { name:"18-Pan Warm Eyeshadow Palette", desc:"18-pan palette with matte and shimmer warm-tone finishes.", cat:"beauty", price:19, stock:35, colors:["Warm Tones"], type:"Makeup", tags:["eyes","makeup"] },
  { name:"Under-Eye Collagen Patches", desc:"30 pairs of collagen and gold eye patches for puffiness.", cat:"beauty", price:16, stock:50, colors:[], type:"Skincare", tags:["eyes","brightening"] },
  { name:"Niacinamide 10% Serum", desc:"10% niacinamide and 1% zinc for pores, oiliness and blemishes.", cat:"beauty", price:14, stock:50, colors:[], type:"Skincare", tags:["pores","brightening"] },
  { name:"Arabica Coffee Body Scrub", desc:"Coffee body scrub with coconut oil and shea butter. 300g.", cat:"beauty", price:11, stock:45, colors:[], type:"Body", tags:["exfoliant","gift"] },
  // ── OUTDOOR (20) ──
  { name:"4-Person Dome Tent", desc:"Waterproof 4-person dome tent with UV protection.", cat:"outdoor", price:75, stock:15, colors:["Green","Orange"], type:"Camping", tags:["camping","adventure"] },
  { name:"60L Hiking Backpack", desc:"Internal frame backpack with rain cover and ventilated back.", cat:"outdoor", price:58, stock:18, colors:["Black","Olive","Blue"], type:"Bag", tags:["hiking","travel"] },
  { name:"Non-Slip Yoga Mat 6mm", desc:"Eco-TPE yoga mat with alignment lines and carry strap.", cat:"outdoor", price:16, stock:40, colors:["Purple","Black","Teal"], type:"Fitness", tags:["yoga","wellness"] },
  { name:"Vacuum Flask 1L Stainless", desc:"Double-wall vacuum flask. Cold 24hr, hot 12hr.", cat:"outdoor", price:18, stock:55, colors:["Black","Silver","Navy"], type:"Hydration", tags:["hydration","travel"] },
  { name:"Portable Gas Grill 2-Burner", desc:"Compact propane 2-burner grill with folding legs.", cat:"outdoor", price:48, stock:20, colors:["Black/Silver"], type:"BBQ", tags:["BBQ","party"] },
  { name:"Folding Camp Chair", desc:"Lightweight aluminium camp chair with cup holder. 150kg.", cat:"outdoor", price:14, stock:45, colors:["Black","Navy","Red"], type:"Furniture", tags:["camping","beach"] },
  { name:"Solar LED Lantern", desc:"USB and solar rechargeable LED lantern with 4 light modes.", cat:"outdoor", price:12, stock:40, colors:["Black","Yellow"], type:"Lighting", tags:["solar","camping"] },
  { name:"Hammock with Tree Straps", desc:"Ultralight nylon hammock with 10ft straps. 300kg capacity.", cat:"outdoor", price:19, stock:30, colors:["Turquoise","Green","Orange"], type:"Camping", tags:["camping","relaxation"] },
  { name:"Cooler Box 30L", desc:"30L cooler box — keeps ice for 5 days.", cat:"outdoor", price:45, stock:15, colors:["White/Blue","Black"], type:"Storage", tags:["BBQ","beach"] },
  { name:"500 Lumen Headlamp", desc:"Rechargeable LED headlamp, 500 lumens, IPX6 waterproof.", cat:"outdoor", price:11, stock:50, colors:["Black"], type:"Lighting", tags:["hiking","camping"] },
  { name:"Aluminium Trekking Poles Pair", desc:"Adjustable anti-shock trekking poles with cork grip.", cat:"outdoor", price:32, stock:25, colors:["Black/Red","Blue/Silver"], type:"Hiking", tags:["hiking","trekking"] },
  { name:"Sleeping Bag -5C Mummy", desc:"3-season mummy sleeping bag rated to -5C. 1200g.", cat:"outdoor", price:39, stock:20, colors:["Blue","Green"], type:"Camping", tags:["camping","winter"] },
  { name:"Aluminium Folding Table", desc:"Lightweight aluminium table with carry bag. 60x45cm.", cat:"outdoor", price:22, stock:25, colors:["Silver"], type:"Furniture", tags:["camping","picnic"] },
  { name:"Carabiner Clip Set 10pc", desc:"D-shape carabiners, 25kN rated. Set of 10.", cat:"outdoor", price:9, stock:60, colors:["Silver","Black","Red"], type:"Climbing", tags:["climbing","hiking"] },
  { name:"Compact Binoculars 10x42", desc:"10x42 waterproof binoculars with phase-coated prisms.", cat:"outdoor", price:55, stock:18, colors:["Black/Green"], type:"Optics", tags:["bird watching","hiking"] },
  { name:"15-in-1 Multi-Tool Knife", desc:"Stainless steel 15-in-1 folding multi-tool with leather pouch.", cat:"outdoor", price:27, stock:30, colors:["Silver"], type:"Tools", tags:["survival","camping"] },
  { name:"Hydration Running Vest 2L", desc:"2L reservoir running vest with multiple pockets.", cat:"outdoor", price:35, stock:22, colors:["Black","Teal"], type:"Running", tags:["running","trail"] },
  { name:"Resistance Bands Set 5pc", desc:"5 latex resistance bands in varying levels.", cat:"outdoor", price:13, stock:65, colors:["Multi"], type:"Fitness", tags:["workout","home gym"] },
  { name:"Speed Jump Rope Steel Cable", desc:"Ball-bearing jump rope with adjustable steel cable.", cat:"outdoor", price:8, stock:75, colors:["Black","Red"], type:"Fitness", tags:["cardio","fitness"] },
  { name:"Single-Burner Camp Stove", desc:"Compact piezo ignition gas camp stove with case.", cat:"outdoor", price:16, stock:35, colors:["Silver/Blue"], type:"Cooking", tags:["camping","cooking"] },
  // ── BOOKS (20) ──
  { name:"Things Fall Apart", desc:"Chinua Achebe's timeless African masterpiece.", cat:"books", price:4, stock:100, colors:[], type:"Fiction", tags:["African literature","classic"] },
  { name:"Atomic Habits", desc:"James Clear's global bestseller on building good habits.", cat:"books", price:6, stock:75, colors:[], type:"Self-Help", tags:["habits","productivity"] },
  { name:"Rich Dad Poor Dad", desc:"Robert Kiyosaki's personal finance classic.", cat:"books", price:5, stock:85, colors:[], type:"Finance", tags:["money","investing"] },
  { name:"Sapiens", desc:"Yuval Noah Harari's brief history of humankind.", cat:"books", price:7, stock:40, colors:[], type:"Non-Fiction", tags:["history","science"] },
  { name:"The Alchemist", desc:"Paulo Coelho's inspirational novel about following your dreams.", cat:"books", price:5, stock:60, colors:[], type:"Fiction", tags:["inspirational","bestseller"] },
  { name:"1984", desc:"George Orwell's dystopian masterpiece. Essential reading.", cat:"books", price:5, stock:70, colors:[], type:"Fiction", tags:["dystopian","classic"] },
  { name:"The Great Gatsby", desc:"F. Scott Fitzgerald's Jazz Age classic. Paperback edition.", cat:"books", price:4, stock:80, colors:[], type:"Fiction", tags:["classic","literature"] },
  { name:"Think and Grow Rich", desc:"Napoleon Hill's classic on the mindset of wealth.", cat:"books", price:5, stock:80, colors:[], type:"Self-Help", tags:["mindset","wealth"] },
  { name:"The 48 Laws of Power", desc:"Robert Greene's masterwork on power, influence and strategy.", cat:"books", price:8, stock:55, colors:[], type:"Strategy", tags:["power","strategy"] },
  { name:"Deep Work", desc:"Cal Newport on the value of undistracted focus.", cat:"books", price:6, stock:50, colors:[], type:"Self-Help", tags:["focus","productivity"] },
  { name:"The Psychology of Money", desc:"Morgan Housel's timeless lessons on wealth and behaviour.", cat:"books", price:7, stock:60, colors:[], type:"Finance", tags:["money","psychology"] },
  { name:"Becoming", desc:"Michelle Obama's powerful and intimate memoir.", cat:"books", price:8, stock:45, colors:[], type:"Biography", tags:["memoir","inspirational"] },
  { name:"The Art of War", desc:"Sun Tzu's ancient text on strategy. Pocket edition.", cat:"books", price:3, stock:95, colors:[], type:"Strategy", tags:["strategy","classic"] },
  { name:"Purple Hibiscus", desc:"Chimamanda Ngozi Adichie's debut novel of love and redemption.", cat:"books", price:5, stock:55, colors:[], type:"Fiction", tags:["African literature","drama"] },
  { name:"Start With Why", desc:"Simon Sinek on how great leaders inspire through purpose.", cat:"books", price:6, stock:55, colors:[], type:"Business", tags:["leadership","motivation"] },
  { name:"The Lean Startup", desc:"Eric Ries on building companies that learn fast.", cat:"books", price:7, stock:40, colors:[], type:"Business", tags:["startup","entrepreneurship"] },
  { name:"Ikigai", desc:"The Japanese secret to a long and happy life.", cat:"books", price:5, stock:65, colors:[], type:"Self-Help", tags:["wellness","Japanese"] },
  { name:"Zero to One", desc:"Peter Thiel on startups and how to build the future.", cat:"books", price:7, stock:45, colors:[], type:"Business", tags:["startup","tech"] },
  { name:"Cant Hurt Me", desc:"David Goggins' raw story of mastering your mind.", cat:"books", price:7, stock:50, colors:[], type:"Memoir", tags:["mindset","motivation"] },
  { name:"The Mountain Is You", desc:"Brianna Wiest on self-sabotage and healing.", cat:"books", price:6, stock:55, colors:[], type:"Self-Help", tags:["wellness","mental health"] },
  // ── TOYS (20) ──
  { name:"Wooden Building Blocks 100pc", desc:"100 natural wood blocks in multiple shapes. Ages 2+.", cat:"toys", price:15, stock:35, colors:["Multi"], type:"Building", tags:["educational","toddler"] },
  { name:"4WD Remote Control Car", desc:"1:16 off-road RC car with rechargeable battery. Ages 6+.", cat:"toys", price:22, stock:25, colors:["Red","Blue","Green"], type:"RC Toys", tags:["RC","boys"] },
  { name:"3-Storey Wooden Doll House", desc:"Wooden doll house with 12 furniture pieces. Ages 3+.", cat:"toys", price:35, stock:15, colors:["Pink/White"], type:"Dolls", tags:["girls","imaginative"] },
  { name:"STEM Science Kit Junior", desc:"50+ experiment STEM kit for ages 8-12 with lab coat.", cat:"toys", price:18, stock:30, colors:["Multi"], type:"Educational", tags:["STEM","science"] },
  { name:"Giant Foam Building Bricks 80pc", desc:"Oversized foam bricks. Safe for toddlers.", cat:"toys", price:19, stock:30, colors:["Multi"], type:"Building", tags:["toddler","building"] },
  { name:"World Map Jigsaw 500-Piece", desc:"Illustrated 500-piece world map with landmarks.", cat:"toys", price:9, stock:40, colors:["Multi"], type:"Puzzle", tags:["educational","family"] },
  { name:"Chess and Checkers Set", desc:"Classic strategy board game in natural wood box.", cat:"toys", price:11, stock:45, colors:["Natural Wood"], type:"Board Game", tags:["classic","family"] },
  { name:"Art and Craft Set 120pc", desc:"120-piece art kit with crayons, watercolours and stickers.", cat:"toys", price:13, stock:50, colors:["Multi"], type:"Creative", tags:["art","creative"] },
  { name:"Soft Plush Elephant 45cm", desc:"Extra-soft stuffed elephant. Machine washable. Ages 0+.", cat:"toys", price:8, stock:60, colors:["Grey","Pink"], type:"Plush", tags:["baby","gift"] },
  { name:"61-Key Electric Piano", desc:"Portable keyboard with 300 tones and LED display. Ages 5+.", cat:"toys", price:55, stock:12, colors:["Black"], type:"Musical", tags:["music","educational"] },
  { name:"Wooden Play Kitchen Set", desc:"Realistic wooden play kitchen with 20 accessories. Ages 3+.", cat:"toys", price:42, stock:15, colors:["White/Wooden"], type:"Play", tags:["imaginative","girls"] },
  { name:"Magnetic Drawing Board", desc:"Mess-free magnetic drawing board with eraser. Ages 3+.", cat:"toys", price:7, stock:65, colors:["Blue","Pink","Green"], type:"Creative", tags:["creative","toddler"] },
  { name:"Dinosaur Figure Set 12pc", desc:"12 hand-painted realistic dinosaur figures. Ages 3+.", cat:"toys", price:14, stock:40, colors:["Multi"], type:"Figures", tags:["boys","collectible"] },
  { name:"Foam Dart Blaster Gun", desc:"High-capacity foam dart blaster with 20 darts. Ages 6+.", cat:"toys", price:11, stock:50, colors:["Orange/Blue"], type:"Action", tags:["outdoor","active"] },
  { name:"Balance Bike 12-inch", desc:"Lightweight 12-inch balance bike. Ages 2-5.", cat:"toys", price:38, stock:18, colors:["Red","Blue","Green"], type:"Ride-On", tags:["outdoor","active"] },
  { name:"Montessori Busy Board", desc:"Wooden sensory activity board with locks, zips and buttons.", cat:"toys", price:23, stock:25, colors:["Natural"], type:"Educational", tags:["Montessori","toddler"] },
  { name:"Glow in the Dark Stars 200pc", desc:"200 peel-and-stick glow stars with moon and planets.", cat:"toys", price:6, stock:80, colors:["Glow Green"], type:"Decor", tags:["bedroom","astronomy"] },
  { name:"Sand Art Activity Kit", desc:"Sand art kit with 12 bottles of coloured sand and 8 frames.", cat:"toys", price:16, stock:30, colors:["Multi"], type:"Creative", tags:["art","creative"] },
  { name:"Marble Run Set 120pc", desc:"120-piece stackable marble run with 4 marbles. Ages 4+.", cat:"toys", price:24, stock:22, colors:["Multi"], type:"Building", tags:["STEM","building"] },
  { name:"Doctor Role Play Kit", desc:"15-piece doctor kit in carry case with stethoscope. Ages 3+.", cat:"toys", price:12, stock:40, colors:["White/Blue"], type:"Role Play", tags:["imaginative","educational"] },
  // ── SPORTS (20) ──
  { name:"Adjustable Dumbbell Set 20kg", desc:"Cast iron adjustable dumbbell set with plates and handles.", cat:"sports", price:49, stock:20, colors:["Black"], type:"Weights", tags:["gym","strength"] },
  { name:"Pro Basketball Outdoor Size 7", desc:"Size 7 rubber outdoor basketball.", cat:"sports", price:19, stock:35, colors:["Orange"], type:"Ball Sports", tags:["basketball","outdoor"] },
  { name:"FIFA Match Football Size 5", desc:"FIFA-quality match football with thermal bonded panels.", cat:"sports", price:22, stock:45, colors:["Black/White","Blue/White"], type:"Ball Sports", tags:["football","match"] },
  { name:"Steel Cable Skipping Rope", desc:"Speed rope with adjustable steel cable and ball bearings.", cat:"sports", price:8, stock:75, colors:["Black","Red"], type:"Cardio", tags:["cardio","HIIT"] },
  { name:"Doorframe Pull-Up Bar", desc:"No-screw doorframe pull-up bar. Supports up to 120kg.", cat:"sports", price:17, stock:35, colors:["Black"], type:"Strength", tags:["home gym","strength"] },
  { name:"High-Density Foam Roller 45cm", desc:"EPP foam roller for muscle recovery and myofascial release.", cat:"sports", price:12, stock:55, colors:["Black","Blue","Pink"], type:"Recovery", tags:["recovery","yoga"] },
  { name:"Resistance Bands 5-Pack", desc:"5-piece latex bands from extra light to extra heavy.", cat:"sports", price:13, stock:65, colors:["Multi"], type:"Resistance", tags:["home gym","rehab"] },
  { name:"Sports Water Bottle 1L BPA-Free", desc:"1L BPA-free bottle with leak-proof flip lid.", cat:"sports", price:9, stock:80, colors:["Black","Blue","Pink","Green"], type:"Hydration", tags:["hydration","gym"] },
  { name:"Gym Gloves Wrist Support", desc:"Half-finger gym gloves with wrist wrap support.", cat:"sports", price:11, stock:60, colors:["Black","Grey","Pink"], type:"Accessories", tags:["gym","lifting"] },
  { name:"Badminton Complete Set", desc:"2 carbon rackets, 3 shuttlecocks and carry bag.", cat:"sports", price:28, stock:25, colors:["Black/Red","Blue/White"], type:"Racket Sports", tags:["badminton","outdoor"] },
  { name:"Graphite Tennis Racket 300g", desc:"Graphite tennis racket, 4-3/8 grip, strung at 55lbs.", cat:"sports", price:34, stock:22, colors:["Black/Yellow","Blue/Black"], type:"Racket Sports", tags:["tennis","outdoor"] },
  { name:"UV Swimming Goggles", desc:"UV-protective anti-fog goggles with adjustable silicone strap.", cat:"sports", price:9, stock:55, colors:["Black","Blue","Clear"], type:"Swimming", tags:["swimming","pool"] },
  { name:"CE Cycling Helmet", desc:"Lightweight CE-certified helmet with 18 ventilation channels.", cat:"sports", price:26, stock:28, colors:["Black","White","Red"], type:"Cycling", tags:["cycling","safety"] },
  { name:"Knee Compression Sleeves Pair", desc:"Medical-grade neoprene knee sleeves for joint support.", cat:"sports", price:16, stock:45, colors:["Black"], type:"Support", tags:["knee","recovery"] },
  { name:"Table Tennis Complete Set", desc:"2 paddles, 6 balls and retractable net for any table.", cat:"sports", price:19, stock:30, colors:["Red/Black"], type:"Table Sports", tags:["table tennis","family"] },
  { name:"Double-Wheel Ab Roller", desc:"Double-wheel ab roller with knee pad for core training.", cat:"sports", price:10, stock:60, colors:["Black","Blue"], type:"Core", tags:["abs","home gym"] },
  { name:"Olympic Wooden Gym Rings", desc:"Wooden gymnastic rings with adjustable 4.5m straps.", cat:"sports", price:22, stock:20, colors:["Natural Wood"], type:"Gymnastics", tags:["calisthenics","strength"] },
  { name:"Reflective Running Armband", desc:"Reflective running armband fits phones up to 7 inches.", cat:"sports", price:7, stock:80, colors:["Black","Blue","Pink"], type:"Accessories", tags:["running","phone"] },
  { name:"Speed Agility Ladder 12-Rung", desc:"12-rung flat speed ladder with carry bag.", cat:"sports", price:14, stock:40, colors:["Yellow","Red"], type:"Training", tags:["agility","speed"] },
  { name:"8-Position Push-Up Board", desc:"Colour-coded 8-position push-up board.", cat:"sports", price:16, stock:35, colors:["Black/Multi"], type:"Strength", tags:["push-ups","home gym"] },
  // ── FURNITURE (20) ──
  { name:"Ergonomic Mesh Office Chair", desc:"Mesh-back chair with lumbar support and adjustable armrests.", cat:"furniture", price:149, stock:12, colors:["Black","Grey"], type:"Chair", tags:["office","ergonomic"] },
  { name:"5-Tier Industrial Bookshelf", desc:"Solid pine bookshelf with industrial metal frame.", cat:"furniture", price:89, stock:10, colors:["Natural/Black","Walnut/Black"], type:"Storage", tags:["storage","industrial"] },
  { name:"Rattan Accent Chair", desc:"Handwoven rattan accent chair with cushioned seat.", cat:"furniture", price:119, stock:8, colors:["Natural","Black"], type:"Chair", tags:["boho","accent"] },
  { name:"Electric Standing Desk 140cm", desc:"Height-adjustable standing desk. 140x70cm. Memory presets.", cat:"furniture", price:239, stock:6, colors:["White","Black","Walnut"], type:"Desk", tags:["ergonomic","office"] },
  { name:"Velvet 2-Seater Sofa", desc:"Compact velvet 2-seater sofa with gold-tone legs.", cat:"furniture", price:299, stock:5, colors:["Emerald","Blush","Navy","Grey"], type:"Sofa", tags:["living room","velvet"] },
  { name:"Solid Oak Extendable Dining Table", desc:"Solid oak extendable dining table. Seats 4-8 people.", cat:"furniture", price:349, stock:4, colors:["Oak","Walnut"], type:"Table", tags:["dining","oak"] },
  { name:"Murphy Wall Bed Queen", desc:"Space-saving queen murphy bed with integrated shelving.", cat:"furniture", price:549, stock:3, colors:["White","Oak"], type:"Bed", tags:["space-saving","bedroom"] },
  { name:"Adjustable Bar Stool Set of 2", desc:"Counter bar stools with footrest and height adjustment.", cat:"furniture", price:79, stock:15, colors:["Black","White","Grey"], type:"Stool", tags:["kitchen","bar"] },
  { name:"3-Door Mirrored Sliding Wardrobe", desc:"3-door mirrored wardrobe with internal rail and shelves.", cat:"furniture", price:399, stock:4, colors:["White","Oak"], type:"Wardrobe", tags:["bedroom","storage"] },
  { name:"4-Piece Rattan Garden Sofa Set", desc:"All-weather rattan garden sofa set with cushions.", cat:"furniture", price:289, stock:6, colors:["Grey/Cream","Brown/Beige"], type:"Outdoor", tags:["garden","outdoor"] },
  { name:"Floating TV Cabinet", desc:"Wall-mounted TV cabinet. Fits up to 65-inch TVs.", cat:"furniture", price:129, stock:8, colors:["White","Walnut","Black"], type:"Cabinet", tags:["living room","storage"] },
  { name:"Bedside Table Set of 2", desc:"Pair of bedside tables with 1 drawer and open shelf.", cat:"furniture", price:89, stock:10, colors:["White","Oak","Black"], type:"Table", tags:["bedroom","storage"] },
  { name:"Round Marble Coffee Table", desc:"Round marble-top coffee table with gold metal legs.", cat:"furniture", price:169, stock:7, colors:["White Marble","Grey Marble"], type:"Table", tags:["living room","luxury"] },
  { name:"Velvet Storage Ottoman", desc:"Button-tufted velvet storage ottoman with wooden legs.", cat:"furniture", price:59, stock:15, colors:["Grey","Emerald","Navy","Blush"], type:"Ottoman", tags:["storage","bedroom"] },
  { name:"King Upholstered Bed Frame", desc:"King-size upholstered frame with button-tufted headboard.", cat:"furniture", price:319, stock:5, colors:["Grey","Cream","Navy"], type:"Bed", tags:["bedroom","luxury"] },
  { name:"6-Panel Bamboo Room Divider", desc:"Folding 6-panel bamboo room divider. 180cm high.", cat:"furniture", price:75, stock:10, colors:["Natural","Black","White"], type:"Room Divider", tags:["storage","divider"] },
  { name:"5-Tier Ladder Shelf", desc:"No-assembly 5-tier lean-to ladder bookshelf.", cat:"furniture", price:69, stock:12, colors:["White/Black","Natural/Black"], type:"Shelf", tags:["storage","modern"] },
  { name:"Giant XL Bean Bag Chair", desc:"Giant XL bean bag with removable washable cover.", cat:"furniture", price:79, stock:12, colors:["Grey","Navy","Brown","Sage"], type:"Chair", tags:["living room","casual"] },
  { name:"3-Door Modern Sideboard", desc:"Modern sideboard with brass handles and slim legs.", cat:"furniture", price:199, stock:6, colors:["White","Walnut","Black"], type:"Cabinet", tags:["dining","storage"] },
  { name:"LED TV Unit 60-inch", desc:"60-inch TV unit with built-in LED strips and 4 compartments.", cat:"furniture", price:149, stock:8, colors:["Black","White"], type:"Cabinet", tags:["living room","modern"] },
  // ── GAMING (20) ──
  { name:"Wireless Gaming Controller", desc:"Bluetooth gamepad with hall-effect joysticks, 20hr battery.", cat:"gaming", price:45, stock:25, colors:["Black","White","Red"], type:"Controller", tags:["controller","multi-platform"] },
  { name:"7.1 Surround Gaming Headset", desc:"Virtual 7.1 surround headset with retractable mic.", cat:"gaming", price:39, stock:28, colors:["Black/Red","Black/Blue"], type:"Headset", tags:["audio","surround"] },
  { name:"16000 DPI RGB Gaming Mouse", desc:"16000 DPI optical mouse with 8 programmable buttons.", cat:"gaming", price:32, stock:30, colors:["Black","White"], type:"Mouse", tags:["FPS","gaming"] },
  { name:"XXL Gaming Mousepad 900x400mm", desc:"900x400mm desk mat with stitched edges and anti-slip base.", cat:"gaming", price:14, stock:55, colors:["Black"], type:"Mousepad", tags:["desk","gaming"] },
  { name:"Full-Size RGB Mechanical Keyboard", desc:"RGB mechanical keyboard with red linear switches.", cat:"gaming", price:49, stock:22, colors:["Black","White"], type:"Keyboard", tags:["gaming","RGB"] },
  { name:"Racing Gaming Chair", desc:"Racing-style gaming chair with lumbar and neck pillow.", cat:"gaming", price:119, stock:10, colors:["Black/Red","Black/Blue","Black/White"], type:"Chair", tags:["ergonomic","setup"] },
  { name:"Monitor Light Bar LED", desc:"Screenbar LED lamp with auto-dimming sensor.", cat:"gaming", price:28, stock:30, colors:["Black","White"], type:"Lighting", tags:["setup","eye care"] },
  { name:"4K USB Capture Card", desc:"4K HDMI capture card for streaming at 60fps.", cat:"gaming", price:36, stock:20, colors:["Black"], type:"Streaming", tags:["streaming","content"] },
  { name:"Dual Controller Charging Dock", desc:"Charges 2 controllers with LED indicator. 2hr full charge.", cat:"gaming", price:19, stock:35, colors:["Black","White"], type:"Accessories", tags:["charging","controller"] },
  { name:"Desk Cable Management Kit", desc:"Complete cable management kit with raceway and ties.", cat:"gaming", price:12, stock:50, colors:["Black","White"], type:"Accessories", tags:["setup","organisation"] },
  { name:"5m Music Sync LED Strip", desc:"App-controlled LED strip with music sync mode.", cat:"gaming", price:16, stock:60, colors:["Multi"], type:"Lighting", tags:["RGB","setup"] },
  { name:"Dual Monitor Arm VESA", desc:"Full tilt/swivel/rotation dual monitor arm.", cat:"gaming", price:44, stock:18, colors:["Black","Silver"], type:"Mount", tags:["monitor","ergonomic"] },
  { name:"6-Fan RGB Laptop Cooling Pad", desc:"RGB cooling stand with 6 fans and adjustable height.", cat:"gaming", price:22, stock:30, colors:["Black","White"], type:"Cooling", tags:["laptop","thermal"] },
  { name:"Controller Thumb Grips 8-Pack", desc:"Silicone thumb grip caps for PS and Xbox controllers.", cat:"gaming", price:5, stock:100, colors:["Black","Blue","Red"], type:"Accessories", tags:["controller","grips"] },
  { name:"2.1 Gaming Speakers RGB", desc:"2.1 surround gaming speakers with subwoofer and RGB.", cat:"gaming", price:55, stock:15, colors:["Black","White"], type:"Speaker", tags:["audio","gaming"] },
  { name:"USB Condenser Streaming Mic", desc:"Cardioid USB mic with pop filter and boom arm.", cat:"gaming", price:39, stock:22, colors:["Black","White","Silver"], type:"Microphone", tags:["streaming","podcast"] },
  { name:"Universal VR Headset Stand", desc:"VR headset stand with controller hooks.", cat:"gaming", price:18, stock:25, colors:["Black","White"], type:"Accessories", tags:["VR","setup"] },
  { name:"Memory Foam Wrist Rest Combo", desc:"Memory foam wrist rest for keyboard and mouse.", cat:"gaming", price:11, stock:55, colors:["Black","Grey","Pink"], type:"Accessories", tags:["ergonomic","comfort"] },
  { name:"HDMI 2.1 Cable 2m", desc:"Ultra high-speed cable. 8K at 60Hz, 4K at 120Hz.", cat:"gaming", price:8, stock:80, colors:["Black"], type:"Cable", tags:["HDMI","4K"] },
  { name:"Phone Controller Clip", desc:"Telescopic phone clip for Xbox and PS controllers.", cat:"gaming", price:9, stock:70, colors:["Black","White"], type:"Accessories", tags:["mobile gaming","controller"] },
  // ── PETS (20) ──
  { name:"Memory Foam Dog Bed Large", desc:"Waterproof-lined orthopedic memory foam dog bed.", cat:"pets", price:38, stock:20, colors:["Grey","Brown","Navy"], type:"Dog", tags:["dog","comfort"] },
  { name:"Stainless Steel Pet Bowl Set", desc:"2 non-slip stainless bowls with stand. S/M/L.", cat:"pets", price:14, stock:45, colors:["Silver","Rose Gold"], type:"Feeding", tags:["dog","cat"] },
  { name:"5-Tier Cat Tree Tower 150cm", desc:"Sisal cat tree with hammock, condo and dangling toys.", cat:"pets", price:55, stock:15, colors:["Beige","Grey"], type:"Cat", tags:["cat","climbing"] },
  { name:"5m Retractable Dog Lead", desc:"Retractable lead with one-button brake. Up to 50kg.", cat:"pets", price:16, stock:40, colors:["Black","Blue","Red"], type:"Dog", tags:["dog","walking"] },
  { name:"Airline-Approved Pet Carrier", desc:"Soft pet carrier with ventilation panels.", cat:"pets", price:29, stock:22, colors:["Black","Beige"], type:"Travel", tags:["travel","cat","dog"] },
  { name:"3L Auto Pet Feeder Programmable", desc:"3-litre auto feeder with up to 4 daily meal schedules.", cat:"pets", price:34, stock:18, colors:["White","Black"], type:"Feeding", tags:["smart","automatic"] },
  { name:"Dog Grooming Kit 7-Piece", desc:"Clippers, comb and nail file grooming kit.", cat:"pets", price:19, stock:30, colors:["Silver"], type:"Grooming", tags:["grooming","dog"] },
  { name:"Level 2 Dog Puzzle Feeder", desc:"Treat-dispensing interactive puzzle toy.", cat:"pets", price:13, stock:40, colors:["Blue","Orange"], type:"Toy", tags:["mental stimulation","dog"] },
  { name:"Self-Cleaning Cat Litter Box", desc:"Automatic self-cleaning litter box with odour filter.", cat:"pets", price:89, stock:10, colors:["White","Grey"], type:"Cat", tags:["cat","hygiene"] },
  { name:"Real-Time GPS Pet Tracker", desc:"Unlimited range GPS tracker with geofence alerts.", cat:"pets", price:29, stock:25, colors:["Black","Orange"], type:"Tech", tags:["GPS","safety"] },
  { name:"Waterproof Dog Raincoat", desc:"Waterproof raincoat with reflective strips. XS-XL.", cat:"pets", price:17, stock:35, colors:["Yellow","Blue","Red"], type:"Clothing", tags:["dog","rain"] },
  { name:"3-Way Cat Tunnel Play Set", desc:"Crinkle cat tunnel with peek-a-boo holes and dangling ball.", cat:"pets", price:11, stock:45, colors:["Grey","Multi"], type:"Toy", tags:["cat","play"] },
  { name:"20L Aquarium Starter Kit", desc:"Complete kit with filter, LED light and thermometer.", cat:"pets", price:42, stock:12, colors:["Black"], type:"Fish", tags:["fish","aquarium"] },
  { name:"Parrot Cage 65cm", desc:"Powder-coated parrot cage with perches and carry handle.", cat:"pets", price:59, stock:10, colors:["Black","White","Rose Gold"], type:"Bird", tags:["bird","parrot"] },
  { name:"Anti-Bloat Slow Feeder Bowl", desc:"Maze slow feeder bowl to reduce bloating.", cat:"pets", price:10, stock:55, colors:["Blue","Orange","Green"], type:"Feeding", tags:["dog","health"] },
  { name:"8-Panel Foldable Pet Playpen", desc:"Foldable metal playpen for dogs and rabbits.", cat:"pets", price:34, stock:15, colors:["Black","Silver"], type:"Containment", tags:["puppy","rabbit"] },
  { name:"Sisal Cat Scratch Post 60cm", desc:"60cm sisal scratch post with hanging toy ball.", cat:"pets", price:12, stock:45, colors:["Beige","Grey"], type:"Cat", tags:["cat","scratch"] },
  { name:"Dental Chew Sticks 60 Pack", desc:"Vet-approved dental chew sticks for dogs.", cat:"pets", price:8, stock:70, colors:[], type:"Health", tags:["dental","dog"] },
  { name:"Waterproof Pet Car Seat Cover", desc:"Waterproof hammock car seat cover. Universal fit.", cat:"pets", price:22, stock:25, colors:["Black","Grey","Tan"], type:"Travel", tags:["car","travel"] },
  { name:"Deluxe Hamster Cage", desc:"Multi-level hamster cage with wheel, tunnels and bottle.", cat:"pets", price:28, stock:18, colors:["White","Clear"], type:"Small Pets", tags:["hamster","cage"] },
  // ── HEALTH (20) ──
  { name:"Digital Blood Pressure Monitor", desc:"Upper arm BP monitor with irregular heartbeat detection.", cat:"health", price:28, stock:30, colors:["White"], type:"Monitor", tags:["blood pressure","heart"] },
  { name:"Fingertip Pulse Oximeter", desc:"OLED display pulse oximeter with lanyard.", cat:"health", price:12, stock:55, colors:["Black","White","Blue"], type:"Monitor", tags:["oxygen","pulse"] },
  { name:"10-Second Digital Thermometer", desc:"Fast digital thermometer for oral and axillary use.", cat:"health", price:6, stock:80, colors:["White","Blue"], type:"Monitor", tags:["temperature","fever"] },
  { name:"Complete Multivitamin 90 Tablets", desc:"23 vitamins and minerals daily multivitamin.", cat:"health", price:14, stock:60, colors:[], type:"Supplement", tags:["vitamins","daily"] },
  { name:"Omega-3 Fish Oil 1000mg", desc:"High-potency omega-3 fish oil softgels. 180 caps.", cat:"health", price:16, stock:50, colors:[], type:"Supplement", tags:["omega-3","heart"] },
  { name:"Whey Protein Powder 1kg", desc:"25g protein per serving whey concentrate.", cat:"health", price:29, stock:35, colors:["Chocolate","Vanilla","Strawberry"], type:"Supplement", tags:["protein","gym"] },
  { name:"Percussion Massage Gun", desc:"6-speed massage gun, 6 attachments, 3hr battery.", cat:"health", price:44, stock:22, colors:["Black","Grey","Pink"], type:"Recovery", tags:["massage","recovery"] },
  { name:"Hot Water Bottle 2L", desc:"Rubber hot water bottle with knitted cover.", cat:"health", price:9, stock:65, colors:["Grey","Pink","Blue"], type:"Wellness", tags:["pain relief","warmth"] },
  { name:"Adjustable Posture Corrector", desc:"Figure-8 posture corrector with breathable fabric.", cat:"health", price:13, stock:50, colors:["Black","Beige"], type:"Support", tags:["posture","back"] },
  { name:"Vitamin D3 Plus K2 Drops", desc:"1000IU D3 with K2 liquid drops. 90 servings.", cat:"health", price:11, stock:60, colors:[], type:"Supplement", tags:["vitamin D","immunity"] },
  { name:"Dual Channel TENS Machine", desc:"20-intensity TENS machine with 8 modes for pain relief.", cat:"health", price:26, stock:25, colors:["White/Blue"], type:"Pain Relief", tags:["pain","muscle"] },
  { name:"Melatonin 5mg Sleep Aid", desc:"5mg melatonin tablets for healthy sleep onset. 90 pack.", cat:"health", price:10, stock:55, colors:[], type:"Supplement", tags:["sleep","melatonin"] },
  { name:"100-Piece First Aid Kit", desc:"Comprehensive first aid kit in hard carry case.", cat:"health", price:18, stock:40, colors:["Red/White"], type:"First Aid", tags:["first aid","emergency"] },
  { name:"Bamboo Tongue Scrapers 3-Pack", desc:"Bamboo tongue scrapers for oral hygiene.", cat:"health", price:6, stock:75, colors:["Natural"], type:"Oral Care", tags:["oral","eco"] },
  { name:"Infrared Ear Thermometer", desc:"1-second ear and forehead thermometer with colour alarm.", cat:"health", price:21, stock:35, colors:["White"], type:"Monitor", tags:["baby","fever"] },
  { name:"Immune Support Gummies 60pk", desc:"Vitamin C, Zinc and Elderberry immune gummies.", cat:"health", price:13, stock:55, colors:[], type:"Supplement", tags:["immunity","vitamin C"] },
  { name:"Cooling Gel Eye Mask", desc:"Reusable gel eye mask for migraines and eye fatigue.", cat:"health", price:9, stock:60, colors:["Blue","Pink","Black"], type:"Wellness", tags:["migraine","eyes"] },
  { name:"Saline Nasal Spray 100ml", desc:"Natural isotonic saline for congestion relief.", cat:"health", price:5, stock:80, colors:[], type:"Nasal", tags:["sinus","cold"] },
  { name:"Magnesium Glycinate 400mg", desc:"Bioavailable magnesium glycinate for sleep and muscles.", cat:"health", price:17, stock:45, colors:[], type:"Supplement", tags:["sleep","muscle"] },
  { name:"Massage Ball Set 3 Sizes", desc:"3 spiky and smooth balls for trigger point relief.", cat:"health", price:11, stock:50, colors:["Black","Blue","Orange"], type:"Recovery", tags:["massage","feet"] },
  // ── STATIONERY (20) ──
  { name:"Genuine Leather A5 Notebook", desc:"Leather A5 notebook with 200 acid-free pages.", cat:"stationery", price:18, stock:40, colors:["Black","Brown","Tan"], type:"Notebook", tags:["journal","writing"] },
  { name:"Fountain Pen with 10 Cartridges", desc:"Cartridge fountain pen with 10 ink cartridges.", cat:"stationery", price:22, stock:30, colors:["Black","Blue","Gold"], type:"Pen", tags:["writing","premium"] },
  { name:"Washi Tape Set 20 Rolls", desc:"20 rolls of decorative washi tape. Assorted patterns.", cat:"stationery", price:11, stock:55, colors:["Multi"], type:"Tape", tags:["craft","journaling"] },
  { name:"Dual-Tip Brush Pen Set 12pc", desc:"12 dual-tip brush pens for calligraphy and lettering.", cat:"stationery", price:14, stock:45, colors:["Multi"], type:"Pen", tags:["calligraphy","art"] },
  { name:"Pastel Sticky Notes 180pk", desc:"180 sticky notes in 6 sizes and 9 pastel colours.", cat:"stationery", price:7, stock:70, colors:["Pastel Multi"], type:"Stickers", tags:["office","planning"] },
  { name:"Undated Weekly Planner A5", desc:"A5 weekly planner with habit tracker and goal pages.", cat:"stationery", price:16, stock:40, colors:["Sage","Blush","Black"], type:"Planner", tags:["planning","productivity"] },
  { name:"Pastel Highlighter Set 10pc", desc:"10-piece pastel highlighter set, chisel and bullet tip.", cat:"stationery", price:8, stock:65, colors:["Pastel Multi"], type:"Highlighter", tags:["studying","office"] },
  { name:"Clear Acrylic Desk Organiser 5pc", desc:"5-piece acrylic organiser set for pens and supplies.", cat:"stationery", price:19, stock:30, colors:["Clear","Black"], type:"Organiser", tags:["desk","organisation"] },
  { name:"Heavy-Duty Stapler 40-Sheet", desc:"Desktop stapler for 40 sheets with staple remover.", cat:"stationery", price:12, stock:40, colors:["Black","Silver","Red"], type:"Office", tags:["office","stapler"] },
  { name:"Kraft Paper Envelope Pack 50", desc:"50 A5 kraft paper envelopes with string closure.", cat:"stationery", price:9, stock:55, colors:["Kraft Brown"], type:"Envelopes", tags:["craft","packaging"] },
  { name:"Gel Ink Pen Set 0.5mm 20pk", desc:"20 fine tip gel pens with quick-dry ink. Assorted colours.", cat:"stationery", price:10, stock:60, colors:["Multi"], type:"Pen", tags:["writing","school"] },
  { name:"Stamp and Ink Set 20 Stamps", desc:"Wooden handle stamp set with 3 ink pads.", cat:"stationery", price:13, stock:35, colors:["Multi"], type:"Craft", tags:["craft","card-making"] },
  { name:"Ruled Index Cards with Box 200pk", desc:"200 index cards with storage box and dividers.", cat:"stationery", price:6, stock:70, colors:["White","Pastel Multi"], type:"Cards", tags:["studying","revision"] },
  { name:"3-Tier Mesh Letter Tray", desc:"Stackable 3-tier mesh wire letter tray.", cat:"stationery", price:15, stock:35, colors:["Black","Rose Gold","Silver"], type:"Organiser", tags:["desk","office"] },
  { name:"Graphite Drawing Pencil Set 24", desc:"24 graphite drawing pencils from 6H to 8B.", cat:"stationery", price:17, stock:30, colors:["Graphite"], type:"Pencil", tags:["drawing","art"] },
  { name:"Neon Sticky Memo Cube 450 Sheets", desc:"450-sheet self-adhesive memo cube in 3 neon colours.", cat:"stationery", price:5, stock:80, colors:["Neon Multi"], type:"Memo", tags:["notes","office"] },
  { name:"A4 Laminator with 10 Pouches", desc:"A4 laminator with 10 pouches. Ready in 3 minutes.", cat:"stationery", price:24, stock:22, colors:["White","Black"], type:"Office", tags:["laminator","office"] },
  { name:"Colour-Coded Tab Dividers 60pk", desc:"60 self-adhesive dividers for ring binders.", cat:"stationery", price:7, stock:65, colors:["Multi"], type:"Filing", tags:["filing","organisation"] },
  { name:"Professional Watercolour Set 36-Pan", desc:"36-pan watercolour set with 2 brushes and palette.", cat:"stationery", price:21, stock:25, colors:["Multi"], type:"Art", tags:["watercolour","art"] },
  { name:"Mini Zink Pocket Photo Printer", desc:"Wireless Zink pocket printer — no ink needed.", cat:"stationery", price:39, stock:18, colors:["White","Pink","Blue"], type:"Printer", tags:["photos","portable"] },
  // ── BABY (20) ──
  { name:"1080p WiFi Baby Monitor", desc:"HD baby monitor with night vision and 2-way audio.", cat:"baby", price:45, stock:18, colors:["White"], type:"Monitor", tags:["safety","wifi"] },
  { name:"Organic Muslin Swaddle 4-Pack", desc:"4 organic cotton muslin swaddles. 120x120cm.", cat:"baby", price:19, stock:40, colors:["White","Sage","Blush"], type:"Swaddle", tags:["organic","newborn"] },
  { name:"Ergonomic Baby Carrier", desc:"Baby carrier with lumbar support. Newborn to 20kg.", cat:"baby", price:55, stock:15, colors:["Grey","Navy","Sage"], type:"Carrier", tags:["babywearing","ergonomic"] },
  { name:"Electric Steam Bottle Steriliser", desc:"Sterilises up to 6 bottles in 6 minutes.", cat:"baby", price:34, stock:20, colors:["White","Blue"], type:"Feeding", tags:["steriliser","hygiene"] },
  { name:"Vibrating Baby Bouncer Rocker", desc:"Baby bouncer with vibration mode and toy arch.", cat:"baby", price:39, stock:15, colors:["Grey","Blue","Pink"], type:"Rocker", tags:["newborn","soothing"] },
  { name:"BPA-Free Teething Rings Set", desc:"4 BPA-free silicone teething rings. Different shapes.", cat:"baby", price:9, stock:60, colors:["Pastel Multi"], type:"Teether", tags:["teething","BPA-free"] },
  { name:"4-in-1 Baby Food Maker", desc:"Steam, blend, defrost and reheat all in one machine.", cat:"baby", price:49, stock:12, colors:["White"], type:"Feeding", tags:["weaning","healthy"] },
  { name:"Foldable Travel Cot with Mattress", desc:"Foldable travel cot with mattress pad and carry bag.", cat:"baby", price:59, stock:10, colors:["Grey","Navy"], type:"Sleeping", tags:["travel","sleep"] },
  { name:"Ergonomic Baby Bath Tub", desc:"Baby bath tub with built-in head support and drain plug.", cat:"baby", price:22, stock:25, colors:["White","Aqua","Pink"], type:"Bath", tags:["bath","newborn"] },
  { name:"Anti-Colic Bottle Set", desc:"Wide-neck anti-colic bottles. 150/260/260ml.", cat:"baby", price:16, stock:40, colors:["Clear","Teal","Pink"], type:"Feeding", tags:["colic","breastfeeding"] },
  { name:"Double-Sided Foam Play Mat 180x180", desc:"Non-toxic foam puzzle play mat. 180x180cm.", cat:"baby", price:27, stock:22, colors:["Pastel","Grey Stars"], type:"Play", tags:["play","crawling"] },
  { name:"Baby Sleep Sack 2-Pack", desc:"2x TOG 1.0 sleep sacks in sizes 0-6M and 6-12M.", cat:"baby", price:21, stock:30, colors:["White","Grey","Blush"], type:"Sleepwear", tags:["sleep","safe"] },
  { name:"Wooden Baby Gym Activity", desc:"Wooden gym with 5 sensory toys and adjustable arch.", cat:"baby", price:32, stock:18, colors:["Natural/Multi"], type:"Play", tags:["sensory","development"] },
  { name:"Electric Nasal Aspirator", desc:"3-level suction aspirator with silicone tips.", cat:"baby", price:18, stock:35, colors:["White/Blue","White/Pink"], type:"Health", tags:["health","cold"] },
  { name:"Reusable Food Pouches 20pk", desc:"20 squeezable silicone food pouches with zip seal.", cat:"baby", price:14, stock:45, colors:["Clear/Green","Clear/Blue"], type:"Feeding", tags:["weaning","eco"] },
  { name:"8-Piece Baby Grooming Kit", desc:"Safety scissors and nail files baby grooming set.", cat:"baby", price:11, stock:50, colors:["White/Pink","White/Blue"], type:"Grooming", tags:["grooming","safety"] },
  { name:"Silicone Suction Bowl Set 4pc", desc:"4 suction-base silicone divided bowls. BPA-free.", cat:"baby", price:13, stock:45, colors:["Sage","Blush","Blue","Yellow"], type:"Feeding", tags:["weaning","BPA-free"] },
  { name:"Universal Pram Rain Cover", desc:"Waterproof rain cover for most buggy models.", cat:"baby", price:16, stock:30, colors:["Clear"], type:"Travel", tags:["pram","rain"] },
  { name:"Natural Rubber Giraffe Teether", desc:"Classic natural rubber teething toy. Ages 0+.", cat:"baby", price:12, stock:40, colors:["Yellow/Brown"], type:"Toy", tags:["teething","classic"] },
  { name:"25-Sound White Noise Baby Machine", desc:"Portable white noise machine with night light.", cat:"baby", price:23, stock:28, colors:["White","Grey"], type:"Sleep", tags:["sleep","white noise"] },
  // ── WATCHES (20) ──
  { name:"Minimalist Stainless Watch", desc:"Stainless steel watch with date window and sapphire crystal.", cat:"watches", price:65, stock:15, colors:["Silver","Rose Gold","Black"], type:"Casual", tags:["premium","gift"] },
  { name:"3-Eye Chronograph Sport Watch", desc:"Chronograph with tachymetre scale and silicone strap.", cat:"watches", price:49, stock:20, colors:["Black","Blue","Red"], type:"Sport", tags:["sport","chronograph"] },
  { name:"Self-Winding Skeleton Watch", desc:"Automatic skeleton watch with exhibition case back.", cat:"watches", price:89, stock:12, colors:["Silver/Brown","Gold/Black"], type:"Automatic", tags:["premium","skeleton"] },
  { name:"Ladies Rose Gold Bracelet Watch", desc:"Rose gold mesh bracelet watch. Japanese quartz movement.", cat:"watches", price:38, stock:25, colors:["Rose Gold","Gold","Silver"], type:"Ladies", tags:["ladies","elegant"] },
  { name:"Military Digital Watch", desc:"Military watch with compass, altimeter and backlight.", cat:"watches", price:34, stock:28, colors:["Black","Olive","Khaki"], type:"Digital", tags:["military","outdoor"] },
  { name:"GPS Smartwatch Fitness Pro", desc:"GPS smartwatch with heart rate, SpO2 and sleep tracking.", cat:"watches", price:79, stock:18, colors:["Black","Silver","Rose Gold"], type:"Smart", tags:["fitness","GPS"] },
  { name:"Classic Leather Strap Watch", desc:"Classic round-face watch with genuine leather strap.", cat:"watches", price:42, stock:25, colors:["Brown","Black","Navy"], type:"Classic", tags:["classic","leather"] },
  { name:"Oversized Fashion Watch", desc:"Bold oversized case fashion watch with textured dial.", cat:"watches", price:28, stock:30, colors:["Gold","Gunmetal","Rose Gold"], type:"Fashion", tags:["fashion","bold"] },
  { name:"GMT Dual Time Zone Watch", desc:"GMT watch with dual time zone and rotating 24hr bezel.", cat:"watches", price:95, stock:10, colors:["Silver/Blue","Gold/Green"], type:"GMT", tags:["travel","professional"] },
  { name:"Kids Waterproof Digital Watch", desc:"Waterproof digital watch for kids with alarm and stopwatch.", cat:"watches", price:12, stock:55, colors:["Pink","Blue","Green","Orange"], type:"Kids", tags:["kids","waterproof"] },
  { name:"Pilot Aviator Watch", desc:"Aviator-style watch with Arabic numerals and luminous hands.", cat:"watches", price:56, stock:18, colors:["Black/Silver","Brown/Gold"], type:"Pilot", tags:["pilot","vintage"] },
  { name:"All-Ceramic Ladies Watch", desc:"All-ceramic ladies watch with mother-of-pearl dial.", cat:"watches", price:72, stock:12, colors:["White","Black"], type:"Ladies", tags:["ceramic","luxury"] },
  { name:"5-Strap NATO Watch Set", desc:"Minimalist watch with 5 interchangeable NATO straps.", cat:"watches", price:32, stock:30, colors:["Silver+Multi"], type:"Casual", tags:["versatile","casual"] },
  { name:"Solar Powered Watch", desc:"Solar watch with 6-month dark reserve.", cat:"watches", price:55, stock:15, colors:["Black","Blue","Silver"], type:"Solar", tags:["eco","solar"] },
  { name:"Ultra-Thin Dress Watch", desc:"5mm case dress watch with alligator-grain leather strap.", cat:"watches", price:47, stock:20, colors:["Gold/White","Silver/Black"], type:"Dress", tags:["formal","slim"] },
  { name:"Automatic 200M Diver Watch", desc:"200M diver with unidirectional bezel and helium valve.", cat:"watches", price:119, stock:8, colors:["Black","Blue","Green"], type:"Diver", tags:["diving","automatic"] },
  { name:"Mechanical Pocket Watch with Chain", desc:"Antique-style mechanical pocket watch with chain.", cat:"watches", price:26, stock:25, colors:["Gold","Silver","Bronze"], type:"Pocket", tags:["vintage","gift"] },
  { name:"Nurse Fob Watch", desc:"Upside-down fob watch with easy-clean silicone bezel.", cat:"watches", price:14, stock:45, colors:["White","Black","Navy","Purple"], type:"Fob", tags:["nurse","medical"] },
  { name:"Hybrid Smartwatch 30-Day Battery", desc:"30-day battery hybrid smartwatch with notifications.", cat:"watches", price:85, stock:12, colors:["Silver/Black","Rose Gold/Nude"], type:"Smart", tags:["hybrid","smart"] },
  { name:"4-Slot Electric Watch Winder", desc:"4-slot watch winder with quiet motor and glass lid.", cat:"watches", price:34, stock:15, colors:["Black","Walnut"], type:"Accessories", tags:["winder","storage"] },
  // ── BAGS (20) ──
  { name:"Full-Grain Leather Tote Large", desc:"Full-grain leather tote with zip top and inner pockets.", cat:"bags", price:79, stock:15, colors:["Black","Tan","Navy"], type:"Tote", tags:["leather","work"] },
  { name:"Waxed Canvas Crossbody Bag", desc:"Waxed canvas crossbody with leather trim.", cat:"bags", price:38, stock:25, colors:["Olive","Navy","Black"], type:"Crossbody", tags:["casual","everyday"] },
  { name:"Hardshell 20-inch Cabin Luggage", desc:"20-inch hardshell spinner with TSA lock.", cat:"bags", price:79, stock:12, colors:["Black","Navy","Rose Gold","Mint"], type:"Luggage", tags:["travel","carry-on"] },
  { name:"Waterproof 25L Laptop Backpack", desc:"Waterproof backpack with USB charging port.", cat:"bags", price:35, stock:30, colors:["Black","Grey","Navy"], type:"Backpack", tags:["laptop","work"] },
  { name:"Mini Quilted Chain Shoulder Bag", desc:"Diamond-quilt mini bag with chain strap and flip closure.", cat:"bags", price:29, stock:35, colors:["Black","Blush","Sage","Camel"], type:"Shoulder Bag", tags:["evening","fashion"] },
  { name:"40L Gym Duffel Bag", desc:"Gym duffel with wet/dry compartment and shoe pocket.", cat:"bags", price:32, stock:28, colors:["Black","Navy","Grey"], type:"Duffel", tags:["gym","sport"] },
  { name:"Handwoven Straw Market Bag", desc:"Natural straw beach bag with leather handles.", cat:"bags", price:22, stock:30, colors:["Natural","Natural/Black"], type:"Beach", tags:["summer","beach"] },
  { name:"Nylon Adjustable Belt Bag", desc:"Multi-zip nylon belt bag for travel and festival.", cat:"bags", price:18, stock:40, colors:["Black","Khaki","Pink","Blue"], type:"Belt Bag", tags:["casual","festival"] },
  { name:"Slim Bifold Leather Card Holder", desc:"8-card-slot bifold leather card holder with cash pocket.", cat:"bags", price:19, stock:50, colors:["Black","Brown","Red"], type:"Purse", tags:["slim","gift"] },
  { name:"Structured Top-Handle Handbag", desc:"Structured handbag with detachable shoulder strap.", cat:"bags", price:55, stock:18, colors:["Black","Camel","Burgundy"], type:"Handbag", tags:["work","elegant"] },
  { name:"Lightweight 12L Drawstring Bag", desc:"Polyester drawstring backpack. Great for gym.", cat:"bags", price:8, stock:70, colors:["Black","Navy","White","Red"], type:"Backpack", tags:["gym","casual"] },
  { name:"24-inch Rolling Weekender Bag", desc:"Rolling duffle with retractable handle and spinner wheels.", cat:"bags", price:55, stock:14, colors:["Black","Navy","Burgundy"], type:"Luggage", tags:["travel","weekend"] },
  { name:"Waterproof Camera Bag", desc:"DSLR bag with padded inserts and tripod holder.", cat:"bags", price:42, stock:16, colors:["Black","Brown"], type:"Camera Bag", tags:["photography","travel"] },
  { name:"Water-Resistant Neoprene Tote", desc:"Zip-top neoprene tote. 15L.", cat:"bags", price:24, stock:35, colors:["Black","Grey","Sage","Blush"], type:"Tote", tags:["beach","versatile"] },
  { name:"Genuine Leather Briefcase", desc:"Leather briefcase with padded laptop sleeve.", cat:"bags", price:89, stock:10, colors:["Black","Dark Brown"], type:"Briefcase", tags:["office","professional"] },
  { name:"Drawstring Bucket Bag", desc:"Slouchy bucket bag with drawstring and inner zip pocket.", cat:"bags", price:34, stock:25, colors:["Tan","Black","Red","Cobalt"], type:"Bucket Bag", tags:["casual","boho"] },
  { name:"Ultralight 22L Packable Daypack", desc:"Packable daypack — folds into its own pocket.", cat:"bags", price:19, stock:40, colors:["Black","Navy","Purple"], type:"Backpack", tags:["travel","packable"] },
  { name:"Vintage Leather Satchel", desc:"Classic satchel with brass buckles and adjustable strap.", cat:"bags", price:62, stock:14, colors:["Brown","Black"], type:"Satchel", tags:["vintage","work"] },
  { name:"Nylon Packing Cube Set 6pc", desc:"6-piece compression packing cube set.", cat:"bags", price:22, stock:35, colors:["Black","Blue","Grey"], type:"Organiser", tags:["travel","packing"] },
  { name:"Thermal Insulated Lunch Bag", desc:"Leak-proof thermal lunch bag. 4L capacity.", cat:"bags", price:14, stock:55, colors:["Black","Grey","Navy","Pink"], type:"Lunch Bag", tags:["lunch","office"] },
  // ── FOOD (20) ──
  { name:"Single-Origin Ground Coffee 500g", desc:"Ethiopian Arabica medium roast. Bright and fruity.", cat:"food", price:12, stock:60, colors:[], type:"Coffee", tags:["coffee","Ethiopian"] },
  { name:"Assorted Herbal Tea Box 40 Bags", desc:"Chamomile, Peppermint, Ginger and more.", cat:"food", price:9, stock:70, colors:[], type:"Tea", tags:["tea","herbal"] },
  { name:"Cold-Pressed Raw Honey 500g", desc:"Raw wildflower honey. No additives. Rich and aromatic.", cat:"food", price:11, stock:55, colors:[], type:"Honey", tags:["natural","honey"] },
  { name:"85% Dark Chocolate Bar 6-Pack", desc:"6-pack 85% cocoa dark chocolate bars. Antioxidant-rich.", cat:"food", price:14, stock:50, colors:[], type:"Chocolate", tags:["dark chocolate","gift"] },
  { name:"Organic Almond Butter 500g", desc:"100% organic almond butter. No palm oil, no added sugar.", cat:"food", price:13, stock:45, colors:[], type:"Nut Butter", tags:["organic","healthy"] },
  { name:"Extra Virgin Olive Oil 750ml", desc:"Cold-pressed Moroccan EVOO. Robust and fruity.", cat:"food", price:14, stock:40, colors:[], type:"Oil", tags:["cooking","Mediterranean"] },
  { name:"Gourmet Spice Blend Set 6pc", desc:"6 globally inspired spice blends: Jerk, Berbere, Ras El Hanout.", cat:"food", price:17, stock:40, colors:[], type:"Spices", tags:["cooking","gift"] },
  { name:"Aged Basmati Rice 2kg", desc:"Extra-long grain aged basmati rice. Fluffy and fragrant.", cat:"food", price:8, stock:80, colors:[], type:"Grains", tags:["rice","staple"] },
  { name:"Dry-Roasted Mixed Nuts 500g", desc:"Almonds, cashews, pistachios and walnuts. No salt.", cat:"food", price:15, stock:55, colors:[], type:"Snacks", tags:["healthy","snacks"] },
  { name:"Sourdough Starter Kit", desc:"Sourdough kit with flour, guide and banneton basket.", cat:"food", price:19, stock:25, colors:[], type:"Baking", tags:["baking","bread"] },
  { name:"Artisan Pasta Gift Box 8 Varieties", desc:"8 varieties of bronze-die artisan Italian pasta.", cat:"food", price:22, stock:30, colors:[], type:"Pasta", tags:["Italian","gift"] },
  { name:"Hot Sauce Collection 5 Bottles", desc:"5 hot sauces from mild to scorching.", cat:"food", price:18, stock:35, colors:[], type:"Condiment", tags:["spicy","gift"] },
  { name:"Honey and Oat Organic Granola 750g", desc:"Honey oat granola with almonds and cranberries.", cat:"food", price:10, stock:60, colors:[], type:"Breakfast", tags:["breakfast","organic"] },
  { name:"Naturally Brewed Soy Sauce 500ml", desc:"Japanese soy sauce naturally brewed and aged 2 years.", cat:"food", price:8, stock:55, colors:[], type:"Condiment", tags:["Japanese","cooking"] },
  { name:"Ceremonial Matcha 100g Uji Japan", desc:"First-flush ceremonial matcha from Uji, Japan.", cat:"food", price:22, stock:30, colors:[], type:"Tea", tags:["matcha","Japanese"] },
  { name:"Cold-Pressed Coconut Oil 1L", desc:"Organic virgin coconut oil for cooking and beauty.", cat:"food", price:11, stock:55, colors:[], type:"Oil", tags:["organic","versatile"] },
  { name:"High-Protein Snack Bar Box 12pk", desc:"12 bars, 20g protein each. Chocolate and Vanilla.", cat:"food", price:17, stock:40, colors:[], type:"Snacks", tags:["protein","gym"] },
  { name:"Premium Dried Fruit Mix 500g", desc:"Mango, pineapple, papaya and dates. No added sugar.", cat:"food", price:10, stock:60, colors:[], type:"Snacks", tags:["snacks","healthy"] },
  { name:"Artisan Scotch Bonnet Sauce 200ml", desc:"Small-batch fermented scotch bonnet pepper sauce.", cat:"food", price:9, stock:45, colors:[], type:"Condiment", tags:["hot sauce","artisan"] },
  { name:"Luxury Gift Hamper", desc:"Hamper with chocolate, honey, jam, tea and crackers.", cat:"food", price:45, stock:15, colors:[], type:"Gift Set", tags:["gift","luxury"] },
];

async function seed() {
  console.log("Clearing existing products...");
  await db.execute("TRUNCATE products RESTART IDENTITY CASCADE");
  console.log(`Inserting ${products.length} products across 20 categories...`);

  const rows = products.map(p => ({
    name: p.name,
    description: p.desc,
    category: p.cat,
    price: p.price,
    currency: "USD",
    imageUrl: img[p.cat],
    images: [] as string[],
    colors: p.colors ?? [],
    productType: p.type,
    rating: parseFloat((4.1 + Math.random() * 0.8).toFixed(1)),
    stock: p.stock,
    sellerName: "AllMart Store",
    tags: p.tags,
  }));

  for (let i = 0; i < rows.length; i += 50) {
    await db.insert(productsTable).values(rows.slice(i, i + 50));
    console.log(`  ${Math.min(i + 50, rows.length)}/${rows.length} inserted`);
  }

  console.log(`\nDone! ${products.length} products seeded across 20 categories.`);
  process.exit(0);
}

seed().catch(e => { console.error(e); process.exit(1); });
