uploads = []
outputs = []

[[generated]]
id = "VjXafdHbdfx20lcu_xVj7"
uri = "file://artifacts/storefront/public/images/storefront-ui.png"
type = "image"
title = "Dark mobile storefront UI"

[[generated]]
id = "vSDXiLeJPZUisoeC2t1Ma"
uri = "file://artifacts/storefront/public/images/ai-orb.png"
type = "image"
title = "Glowing AI Orb"

[[generated]]
id = "7p_S--6iY27ABAaNx-4GL"
uri = "file://artifacts/storefront/public/images/bg-abstract.png"
type = "image"
title = "Dark purple abstract background"
