import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import productsRouter from "./products";
import cartRouter from "./cart";
import ordersRouter from "./orders";
import chatRouter from "./chat";
import adminRouter from "./admin";
import adminProductsRouter from "./admin-products";
import storageRouter from "./storage";
import passwordResetRouter from "./password-reset";
import bankSettingsRouter from "./paystack";
import stripeRouter from "./stripe";
import notificationsRouter from "./notifications";
import supportRouter from "./support";
import emailRouter from "./email";
import cashbackRouter from "./cashback";
import landingPagesRouter from "./landing-pages";
import visitorsRouter from "./visitors";
import telegramRouter from "./telegram";
import usersAdminRouter from "./users-admin";
import sitemapRouter from "./sitemap";
import ordersExportRouter from "./orders-export";
import profileRouter from "./profile";
import referralRouter from "./referral";
import adminReferralsRouter from "./admin-referrals";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(productsRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(chatRouter);
router.use(adminRouter);
router.use(adminProductsRouter);
router.use(storageRouter);
router.use(passwordResetRouter);
router.use(bankSettingsRouter);
router.use(stripeRouter);
router.use(notificationsRouter);
router.use(supportRouter);
router.use(emailRouter);
router.use(cashbackRouter);
router.use(landingPagesRouter);
router.use(visitorsRouter);
router.use(telegramRouter);
router.use(usersAdminRouter);
router.use(sitemapRouter);
router.use(ordersExportRouter);
router.use(profileRouter);
router.use(referralRouter);
router.use(adminReferralsRouter);

export default router;
